### Vamshi Krishna Meriga

# ISM 5136 - Data Analytics and Mining for Business

## Lab Session: Numpy Introduction

### Overview:
This lab covers operations related to basic Numpy operations and methods / functions.

### Task:
The code cells in this notebook have been left blank. Your task is to complete these cells and provide the execution results. The corresponding question text for each code cell is provided above the cell. Once you have completed the lab, you should publish your notebook code (the code in the .ipynb file) as a "<u>Secret Gist</u>" on your GitHub repository and obtain the Gist ID.

### Submission Format:
There are two deliverables of this lab: 1) the Gist ID and 2) the completed .ipynb file. Both of these should be submitted on Canvas using the corresponding lab submission link by the due date indicated on Canvas.

### Important: Do <u>not</u> forget to run the cells before submitting your work.


### Questions: Please note that there are multiple steps in each question. You can run each step individually (before moving on to the next one) to make sure that your results are correct.

#### 1. Please complete the steps below.
* Create an array (Numpy ndarray) of integers between 0 and 10.
* Replace the even numbers in the array with -1 and print out the result.

##### Hints:
1. <span style="color: black; background: black; span:hover { color: white}">You can use fancy or boolean indexing (i.e., pass an array to the original array as an index) and do the assignment in the same line</span>

In [2]:
import numpy as np
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a[a%2==0]=-1
a

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9])

#### 2. Please complete the steps below.
* Create an array of integers between 0 and 30.
* Obtain all the elements that are greater than 10 and that can be divided by 9 from this array. Store the output as a <u>list</u> and print it out.

In [5]:
a = np.arange(1,30)
b=[]
for i in a:
    if i>10 and i%9==0:
        b.append(i)

In [35]:
print(b)

[18, 27]


#### 3. Please complete the steps below.
* Create a 2D array in the following form:<br>
[[1, 5, 12], <br>
[3, 2, 8], <br>
[19, 4, 9]]
* Swap columns 1 and 3 and copy the re-arranged data into a new array. Print out the new array.
* Swap rows 2 and 3 and copy the re-arranged data into a new array. Print out the new array.
* Sort the rows in the original array by the 2nd column, while preserving the relationship within row values.
  * Notice that a simple sort method/function would not work here as by default "sort" treats each row/column as independent.
  * Hint: <span style="color: black; background: black; span:hover { color: white}">You can use argsort to find sorted indices and then pass these values to the array using fancy indexing.</span>

In [14]:
import numpy as np
arr = np.array([[1,5,12],[3,2,8],[19,4,9]])


8

In [6]:
len(arr)

3

In [17]:
arr = np.array([[1,5,12],[3,2,8],[19,4,9]])
k=arr
k[:,[0,2]]=k[:,[2,0]]
print(k)
p=arr
p[[1,2],:]=p[[2,1],:]
print(p)
c=p
c=c[c[:,1].argsort()]
print(c)


[[12  5  1]
 [ 8  2  3]
 [ 9  4 19]]
[[12  5  1]
 [ 9  4 19]
 [ 8  2  3]]
[[ 8  2  3]
 [ 9  4 19]
 [12  5  1]]


In [82]:
arr[:,[0,2]]=arr[:,[2,0]]
arr

array([[ 1,  5, 12],
       [ 3,  2,  8],
       [19,  4,  9]])

#### 4. Please complete the steps below.
* Initialize two objects: 1) a 10x2 numpy array filled with zeros, 2) a list of integers between 10 and 20.
* Iterate over the list (for loop) and modify the values in the array as follows:
  * If the list element is an even number, assign value 1 to the 1st column of the corresponding index in the array
  * If the list element is an odd number, assign value 1 to the 2nd column of the corresponding index in the array
* For instance, the first element in the list is 10, an even number, therefore array[0,0] should be 1.
* Print out the modified array.

In [21]:
arr4 = np.zeros((10,2))
a=[i for i in range(10,20)]
for i in range(len(a)):
    if a[i]%2==0:
        arr4[i][0]=1
    else:
        arr4[i][1]=1
arr4

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [84]:
intlist = np.arange(11,20)
intlist

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
for i in intlist:
    if i%2==0:
        arr4=()

#### 5. Please complete the steps below.
* Initialize a 1D array with the following integers: 15,12,2,43,12,6,6,15,8,2
* Some of the numbers above are repeated. Return a new array that includes all the numbers from the original array, but without any duplicates.
* Find the duplicated elements in the original array and print them out.

##### Hints:
1. <span style="color: black; background: black; span:hover { color: white}">You can use the unique() function and its parameters.</span>

In [53]:
arr1 = np.array([15,12,2,43,12,6,6,15,8,2])

In [54]:
uniques,dup = np.unique(arr1,return_counts=True)
uniques

array([ 2,  6,  8, 12, 15, 43])

In [55]:
duplicates = uniques[dup>1]
duplicates

array([ 2,  6, 12, 15])

#### 6. Data Question: Import the "iris_full.csv" dataset into a numpy array, while skipping the 1st row (feature names). The data contains 50 samples from each of three species of Iris flowers (Setosa, Verginica, and Versicolor). Four features were measured for each sample.

In [24]:
#arr2 = np.loadtxt('C:\Users\VenkatBhaskar\Downloads\iris_full.csv',delimiter=',',skiprows=1,dtype='str')
arr2=np.loadtxt("C:/Users/VenkatBhaskar/Downloads/iris_full.csv",delimiter=',',skiprows=1,dtype='str')

In [63]:
arr2

array([['1', '0.2', '1.4', '3.5', '5.1', 'Setosa'],
       ['1', '0.2', '1.4', '3', '4.9', 'Setosa'],
       ['1', '0.2', '1.3', '3.2', '4.7', 'Setosa'],
       ['1', '0.2', '1.5', '3.1', '4.6', 'Setosa'],
       ['1', '0.2', '1.4', '3.6', '5', 'Setosa'],
       ['1', '0.4', '1.7', '3.9', '5.4', 'Setosa'],
       ['1', '0.3', '1.4', '3.4', '4.6', 'Setosa'],
       ['1', '0.2', '1.5', '3.4', '5', 'Setosa'],
       ['1', '0.2', '1.4', '2.9', '4.4', 'Setosa'],
       ['1', '0.1', '1.5', '3.1', '4.9', 'Setosa'],
       ['1', '0.2', '1.5', '3.7', '5.4', 'Setosa'],
       ['1', '0.2', '1.6', '3.4', '4.8', 'Setosa'],
       ['1', '0.1', '1.4', '3', '4.8', 'Setosa'],
       ['1', '0.1', '1.1', '3', '4.3', 'Setosa'],
       ['1', '0.2', '1.2', '4', '5.8', 'Setosa'],
       ['1', '0.4', '1.5', '4.4', '5.7', 'Setosa'],
       ['1', '0.4', '1.3', '3.9', '5.4', 'Setosa'],
       ['1', '0.3', '1.4', '3.5', '5.1', 'Setosa'],
       ['1', '0.3', '1.7', '3.8', '5.7', 'Setosa'],
       ['1', '0.3', '1.5

#### 6.1. Please complete the steps below:
* Subset columns 2 to 5 into a new array called x. Then, convert array x to "float" data type.
* Subset the last column into a new array called yStr.

In [26]:
x = np.array(arr2[:,1:5],dtype='float')
x

array([[0.2, 1.4, 3.5, 5.1],
       [0.2, 1.4, 3. , 4.9],
       [0.2, 1.3, 3.2, 4.7],
       [0.2, 1.5, 3.1, 4.6],
       [0.2, 1.4, 3.6, 5. ],
       [0.4, 1.7, 3.9, 5.4],
       [0.3, 1.4, 3.4, 4.6],
       [0.2, 1.5, 3.4, 5. ],
       [0.2, 1.4, 2.9, 4.4],
       [0.1, 1.5, 3.1, 4.9],
       [0.2, 1.5, 3.7, 5.4],
       [0.2, 1.6, 3.4, 4.8],
       [0.1, 1.4, 3. , 4.8],
       [0.1, 1.1, 3. , 4.3],
       [0.2, 1.2, 4. , 5.8],
       [0.4, 1.5, 4.4, 5.7],
       [0.4, 1.3, 3.9, 5.4],
       [0.3, 1.4, 3.5, 5.1],
       [0.3, 1.7, 3.8, 5.7],
       [0.3, 1.5, 3.8, 5.1],
       [0.2, 1.7, 3.4, 5.4],
       [0.4, 1.5, 3.7, 5.1],
       [0.2, 1. , 3.6, 4.6],
       [0.5, 1.7, 3.3, 5.1],
       [0.2, 1.9, 3.4, 4.8],
       [0.2, 1.6, 3. , 5. ],
       [0.4, 1.6, 3.4, 5. ],
       [0.2, 1.5, 3.5, 5.2],
       [0.2, 1.4, 3.4, 5.2],
       [0.2, 1.6, 3.2, 4.7],
       [0.2, 1.6, 3.1, 4.8],
       [0.4, 1.5, 3.4, 5.4],
       [0.1, 1.5, 4.1, 5.2],
       [0.2, 1.4, 4.2, 5.5],
       [0.2, 1

In [27]:
yStr = arr2[:,5:]
yStr

array([['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Setosa'],
       ['Versicolor'],
       ['Versicolor'],
    

#### 6.2. Please complete the steps below:
* Create an array named "y" that stores the integer value representations of yStr observations. In other terms, convert categorical y values to indicator ones. Each unique value in yStr should be encoded as an integer.
  * For instance, if yStr = array([Setosa,Setosa,Verginica]), then y = array([0,0,1])
* Do not use hard coding.

In [40]:
from sklearn.preprocessing import LabelBinarizer
a=LabelBinarizer()
c=a.fit_transform(yStr)
c

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0,

#### 6.3. Please complete the steps below:
* Combine x and y arrays along axis 1 (horizontally) into a new array called combinedArr

In [61]:
# Enter your answer to the question above in this cell
t=np.concatenate((x,c),axis=1)
t.shape

(150, 7)

#### 6.4. Please complete the steps below:
* Split both x and y arrays into two parts (train and test). So, you should have 4 new arrays: 1) xTrain, 2)xTest, 3) yTrain, 4) yTest.
  * 70% of the data should go into the train dataset and 30% of the data should go into the test dataset. Allocation should be made randomly.
  * When splitting the data, the order of the observations across the x and y arrays should be preserved.
  * For instance, if you assign the 2nd observation into the test dataset, then both xTest and yTest should include the 2nd observation from their original arrays.
  * Do <u>NOT</u> use pre-built functions from external packages (e.g., scikit-learn). Only Numpy and plain Python functions are allowed.

##### Hints:
1. <span style="color: black; background: black; span:hover { color: white}">Numpy's random.choice function might be helpful. </span>
1. <span style="color: black; background: black; span:hover { color: white}">Pay attention to sampling with replacement vs. sampling without replacement.</span>

In [68]:
# Enter your answer to the question above in this cell.
xTrain=t[:105,:4]
xTest=t[105:,:4]
yTrain=t[:105,4:]
yTrain=t[:105,4:]

#### 6.5. Please complete the steps below:
* Find the mean of each column in xTest.
* Find the maximum value of each row in xTest.

In [71]:
# Enter your answer to the question above in this cell.
a=np.mean(xTest)
b=np.amax(xTest,axis=1)

array([7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5, 7.7,
       7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2, 7.4,
       7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8, 6.8,
       6.7, 6.7, 6.3, 6.5, 6.2, 5.9])